Repository jinx-vi-0/passop, pull requests merged in 2024-10, with the labels that each got.

#5 Worked on #4 "Readme.md"
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  backend/.gitignore
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#12 Add Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, Level-1

#16 Added password validation
  src/components/Manager.jsx
Labels: gssoc-ext, Level-2

#29 Added the password generator feature
  src/components/Manager.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level-2

#35 issue : #33 added update button
  src/components/Manager.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, Level-1

#41 Fixes : #26 Added the Import and export option to the NavBar
  backend/server.js
  src/components/Manager.jsx
  src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#44 Better and responsive UI for the Homepage.
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/components/Manager.jsx
  src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#55 fixed delete issue
  src/components/Manager.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#59 Updated
  Dockerfile
Labels: gssoc-ext, hacktoberfest-accepted, level1

#67 #64 updated passwordgen function
  src/components/Manager.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#76 the bug which was causing problem while updating the data is found and resolved.
  backend/server.js
  src/components/Manager.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#86 Set up a firebase sign-in sign-up feature
  backend/server.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/components/SignIn.jsx
  src/components/SignUp.jsx
  src/components/UserAccount.jsx
  src/contexts/authContext/index.jsx
  src/firebase/auth.js
  src/firebase/firebase.js
  src/main.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#73 Impoorting Hash fix #62
  backend/server.js
  src/components/Manager.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#96 Added backlink to homepage in Title
  src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#97 Added Eye for password toggling
  package-lock.json
  package.json
  src/components/SignIn.jsx
  src/components/SignUp.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#99 Improved mobile ui
  src/components/Manager.jsx
  src/components/Navbar.jsx
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#100 Enhance Footer with Social Media Links and Detailed Information
  package-lock.json
  package.json
  src/components/Footer.jsx
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#113 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#115 Navbar Alignment Update (Issue #108)
  package-lock.json
  package.json
  src/components/Navbar.jsx
  src/components/UserAccount.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#126 Fixes #110 : The signIn Button in UI
  src/components/Navbar.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#129 Fixed the github workflows with greetings
  .github/workflows/greetings.yml
  .github/workflows/pr-checker.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#120 Bug: Decrypt Function Fails Due to Incorrect Parameter Passing
  backend/package-lock.json
  backend/package.json
  backend/server.js
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level1
